FROM digichange/php:7.3

RUN mkdir /storage/framework/cache && chown -R www-data:www-data /storage/framework/cache
RUN mkdir /storage/framework/views && chown -R www-data:www-data /storage/framework/views
RUN mkdir /storage/framework/sesions && chown -R www-data:www-data /storage/framework/sessions
