version: '3'

services:

  php:
    container_name: cards_php_1
    build: docker/php
    ports:
     - "8115:80"
    volumes:
     - .:/var/www/html
     - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
     - ./docker/apache:/etc/apache2/sites-enabled:ro
    networks:
     - cardsnet

  redis:
    container_name: cards_redis_1
    image: redis:alpine
    ports:
      - "6315:6379"
    networks:
     - cardsnet

  db:
    container_name: cards_db_1
    image: postgres:12.1
    ports:
     - "5415:5432"
    environment:
      POSTGRES_PASSWORD: the-cards
      POSTGRES_DB: the-cards
      POSTGRES_USER: the-cards
    volumes:
     - data:/var/lib/postgresql/data
    networks:
     - cardsnet

  mail:
    container_name: cards_mail_1
    image: mailhog/mailhog:latest
    ports:
     - "8015:8025"
    networks:
     - cardsnet

  s3:
    container_name: cards_s3_1
    image: minio/minio:latest
    ports:
      - "9015:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: 12345678
    volumes:
      - s3:/data
    networks:
     - cardsnet
    command: server /data

networks:
  cardsnet:
    driver: "bridge"

volumes:
  data:
    driver: "local"
  s3:
    driver: "local"
